name: Build
'on':
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: '${{ secrets.SONAR_TOKEN }}'
          SONAR_HOST_URL: '${{ secrets.SONAR_HOST_URL }}'
      - uses: 'sonarsource/sonarqube-quality-gate-action@master'
        env:
          SONAR_TOKEN: '${{ secrets.SONAR_TOKEN }}'
      - name: npm install dependency
        run: npm install
      - name: Install Trivy
        run: trivy fs . > trivyfs.txt
      - name: Docker build and push
        run: |
          # Run commands to build and push Docker images
          docker build -t tic-tac-toe .
          docker tag tic-tac-toe arif351/tic-tac-toe:latest
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push arif351/tic-tac-toe:latest
        env:
          DOCKER_CLI_ACI: 1

